"""Explore clustering from frozen features; does not publish scores."""

import argparse
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    output_dir = ROOT / ".local/research/clustering" / datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    output_dir.mkdir(parents=True, exist_ok=False)
    print(f"Experiment output: {output_dir}")

    #Implement clustering here
    # -*- coding: utf-8 -*-
    """clustering.ipynb

    Automatically generated by Colab.

    Original file is located at
        https://colab.research.google.com/drive/1ClmNOY-NYZA__C3lqrliwu55cDk6NlFC
    """

    import pandas as pd
    import matplotlib.pyplot as plt
    from sklearn.cluster import KMeans
    from sklearn.preprocessing import StandardScaler
    import seaborn as sns

    # Load your cleaned dataset
    df = pd.read_csv(ROOT / "data/baseline/clustering/features.csv")

    # Inspect the structure
    df.head()

    X = df[['gpi_score', 'ppi_score', 'gti_score', 'pvi_score']]

    inertias = []
    K_range = range(2, 11)

    for k in K_range:
        model = KMeans(n_clusters=k, random_state=42)
        model.fit(X)
        inertias.append(model.inertia_)

    plt.figure(figsize=(6,4))
    plt.plot(K_range, inertias, 'o-', linewidth=2)
    plt.xlabel("Number of Clusters (k)")
    plt.ylabel("Inertia")
    plt.title("Elbow Method for Optimal k")
    plt.savefig(output_dir / "elbow_plot.png", bbox_inches='tight', dpi=300)
    plt.close()

    k = 5  # adjust after looking at the elbow plot
    model = KMeans(n_clusters=k, random_state=42)
    df['cluster'] = model.fit_predict(X)

    # Inspect cluster centroids
    centroids = pd.DataFrame(model.cluster_centers_, columns=X.columns)
    centroids


    # Create a scatter plot matrix
    pairplot = sns.pairplot(df, vars=X.columns, hue='cluster', palette='viridis')
    plt.suptitle('Scatter Plot Matrix of Clusters', y=1.02)
    pairplot.savefig(output_dir / "scatter_matrix.png", bbox_inches='tight', dpi=300)
    plt.close()

    for cluster_id in sorted(df['cluster'].unique()):
        countries_in_cluster = df[df['cluster'] == cluster_id]['iso3'].tolist()
        print(f"Cluster {cluster_id}: {countries_in_cluster}")

    summary = df.groupby('cluster')[X.columns].mean()
    summary

    df.to_csv(output_dir / "clustering_output.csv", index=False)


if __name__ == "__main__":
    main()
