#Implement clustering here
# -*- coding: utf-8 -*-
"""clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ClmNOY-NYZA__C3lqrliwu55cDk6NlFC
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import seaborn as sns

# Load your cleaned dataset
df = pd.read_csv("clustering/data/clustering_ready.csv")

# Inspect the structure
df.head()

X = df[['gpi_score', 'ppi_score', 'gti_score', 'pvi_score']]

inertias = []
K_range = range(2, 11)

for k in K_range:
    model = KMeans(n_clusters=k, random_state=42)
    model.fit(X)
    inertias.append(model.inertia_)

plt.figure(figsize=(6,4))
plt.plot(K_range, inertias, 'o-', linewidth=2)
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia")
plt.title("Elbow Method for Optimal k")
plt.savefig("clustering/output/elbow_plot.png", bbox_inches='tight', dpi=300)
plt.close()

k = 6  # adjust after looking at the elbow plot
model = KMeans(n_clusters=k, random_state=42)
df['cluster'] = model.fit_predict(X)

# Inspect cluster centroids
centroids = pd.DataFrame(model.cluster_centers_, columns=X.columns)
centroids


# Create a scatter plot matrix
pairplot = sns.pairplot(df, vars=X.columns, hue='cluster', palette='viridis')
plt.suptitle('Scatter Plot Matrix of Clusters', y=1.02)
pairplot.savefig("clustering/output/scatter_matrix.png", bbox_inches='tight', dpi=300)
plt.close()

for cluster_id in sorted(df['cluster'].unique()):
    countries_in_cluster = df[df['cluster'] == cluster_id]['iso3'].tolist()
    print(f"Cluster {cluster_id}: {countries_in_cluster}")

summary = df.groupby('cluster')[X.columns].mean()
summary

df.to_csv("clustering/data/clustering_output.csv", index=False)